create database OM;
show databases;
use om;
create table Intrebari (Id int not null auto_increment, Intrebare varchar(255), primary key (Id))engine='MyISAM'; 
show tables;
insert into intrebari (Intrebare) values ('CE');
select *from intrebari;
truncate table intrebari;
delete from intrebari where Id = 3;
alter table intrebari auto_increment = 3;
drop table Intrebari;
select max(Id) from intrebari;
create table raspunsuri (Id int not null auto_increment primary key, Raspuns_1 varchar(255) not null, Raspuns_2 varchar (255) not null, Raspuns_3 varchar(255), Raspuns_4 varchar(255))engine='MyISAM';
drop table raspunsuri;
describe raspunsuri;
select *from raspunsuri;
alter table raspunsuri auto_increment = 4;
update intrebari SET Intrebare = "Ma iei de nevasta?" where Id = 2;
create table Adev_sau_Fals (Id int not null auto_increment primary key, Raspuns_1 bool not null, Raspuns_2 bool not null, Raspuns_3 bool, Raspuns_4 bool)engine='MyISAM';
insert into Adev_sau_Fals (Raspuns_1, Raspuns_2, Raspuns_3, Raspuns_4) values(false, false, false, false);
select *from Adev_sau_Fals;